services:
  mysql:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apv_app
    ports:
      - "3306:3306"
    volumes:
      - apv_app_data:/var/lib/mysql

volumes:
  apv_app_data:

